import Head from 'next/head'
import { collection, doc, getDoc } from "firebase/firestore";
import {db} from '../services/firebase';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { Loading, NotFound } from '@/components/elements';
import Plyr, { PlyrSource} from "plyr-react"
import "plyr-react/plyr.css"

interface VideoPageUI {
  videoUrl: string;
  calendlyUrl: string;
}

export default function VideoPage() {

  const router = useRouter()
  const videoId: string = router.query.id as string;
  const [data, setData] = useState<VideoPageUI | null>(null);
  const [isLoading, setLoading] = useState<boolean>(false);
  
  const fetchData = async () => {
    if (!db || !videoId) return;
    const docRef = doc(db, "gifs", videoId);
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      
      setData({
        calendlyUrl: docSnap.data().calendlyUrl,
        videoUrl: docSnap.data().url,
      })
    }
    else {
      console.log("No Such Document");
    }
    setLoading(false)
}

useEffect(()=>{
  setLoading(true);
  fetchData();
}, [videoId])


return <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.plyr.io/3.7.8/plyr.css" />
      </Head>
      <main className='flex flex-row justify-between items-center p-6 min-h-screen w-full'>
        {isLoading && 
        <div className='mx-auto'>
          <Loading />
        </div>
        }
        {!isLoading && data && <div className='flex flex-col items-center justify-center w-full h-full relative'>
          {/* <video id="player" controls crossOrigin="anonymous" playsInline width="320" height="240">
            <a target="_blank" href={data.calendlyUrl} className='text-white absolute top-4 cursor-pointer bg-[#3D56B0] shadow-md p-2 rounded-lg bg-opacity-70 z-30'>
              Book on Calendly
            </a>
            <source src={data.videoUrl} type="video/mp4" />
            
            Your browser does not support the video tag.
          </video> */}
          <Plyr source={{
            type: 'video',
            sources: [
              {
                src: data.videoUrl,
                type: 'video/mp4',
              }
            ]
          }}>
            <a target="_blank" href={data.calendlyUrl} className='text-white absolute top-4 cursor-pointer bg-[#3D56B0] shadow-md p-2 rounded-lg bg-opacity-70 z-30'>
              Book on Calendly
            </a>
          </Plyr>
        </div>
        }
        {!isLoading && !data && <div className='mx-auto'>
          <NotFound />
          </div>}
      </main>
    </>
}