import Head from 'next/head'

export default function VideoPage() {
return <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-between items-center p-6 min-h-screen'>
        <div className='text-white'>
        Video page here
        </div>
      </main>
    </>
}