import Head from 'next/head'
import { collection, doc, getDoc } from "firebase/firestore";
import { db } from '../services/firebase';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/router';
import { Loading, NotFound } from '@/components/elements';
import MuxPlayer from "@mux/mux-player-react";

interface VideoPageUI {
  videoUrl: string;
  calendlyUrl: string;
}

export default function VideoPage() {

  const router = useRouter()
  const videoId: string = router.query.id as string;





  return <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://cdn.plyr.io/3.7.8/plyr.css" />
    </Head>
    <main className='flex flex-row justify-between items-center p-0 min-h-screen w-full bg-gradient-to-tl from-[#DDFE6B] to-[#FFF170]'>
      <MuxPlayer
        streamType="on-demand"
        playbackId="KFAJMssW02feBDvM00LUpjCDmMjtN201NARf9MwMstyTrU"
        metadata={{
          video_id: "video-id-54321",
          video_title: "Test video title",
          viewer_user_id: "user-id-007",
        }}
      />
    </main>
  </>
}